[ITA-281] Temporarily disable git check after build.

diff --git a/scripts/jenkins/Makefile.jenkins b/scripts/jenkins/Makefile.jenkins
--- a/scripts/jenkins/Makefile.jenkins
+++ b/scripts/jenkins/Makefile.jenkins
@@ -11,14 +11,14 @@ build-h2o-3:
 	@echo
 	@echo "+--Building--+"
 	./gradlew build -x test $$ADDITIONAL_GRADLE_OPTS
-	@echo "+--Git Diff Check--+"
-	if [[ $$(git diff) ]]; then \
-		echo "Non-zero git diff after running gradlew build:"; \
-		git diff; \
-		exit 1; \
-	fi
-	@echo "+--Gradle Check--+"
-	./gradlew -PdoCheckStyle check -x test $$ADDITIONAL_GRADLE_OPTS
+#	@echo "+--Git Diff Check--+"
+#	if [[ $$(git diff) ]]; then \
+#		echo "Non-zero git diff after running gradlew build:"; \
+#		git diff; \
+#		exit 1; \
+#	fi
+#	@echo "+--Gradle Check--+"
+#	./gradlew -PdoCheckStyle check -x test $$ADDITIONAL_GRADLE_OPTS
 
 warmup-caches:
 	@$(MAKE) -f $(THIS_FILE) build-h2o-3
